GET http://localhost:3000/peleadores?race=Namekian HTTP/1.1

###

GET http://localhost:3000/peleadores/2 HTTP/1.1

###
POST http://localhost:3000/peleadores 
Content-Type: application/json

{
    "sql":"select * from users",
    "id":11,
    "name":"VANESA",
    "ki": 111,
    "maxKi":"543 millones",
    "race":"Peleador",
    "gender":"Masculino",
    "description":"Soy un huantinito",
    "image":"https://i.ebayimg.com/images/g/4goAAOSwMyBe7hnQ/s-l1200.webp",
    "affiliation":"Lucma"
}

###
PATCH http://localhost:3000/peleadores/1 HTTP/1.1
Content-Type: application/json

{
    "name":"Carlos",
    "gender":"Medio medio",
    "description":"1232"
    
}

###
DELETE  http://localhost:3000/peleadores/1 HTTP/1.1
